baseurl = "http://juju-sapphire.github.io"
languageCode = "en-us"
title = "The Juju Sapphire team"
theme = "blackburn"
publishdir = "public"
builddrafts = true

canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Making Juju more awesome"
  # brand = "<img src='/img/logo.png'>"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.

  # Techie
  github = "juju-sapphire"